### PR TITLE
interface, logging, process management, and testing improvements, as well as bug fixes

### PR DESCRIPTION
**Pull request by oscarbatori**
This pull request addresses the following issues:
- #47 implements more robust handling of server processes, including cleaning up on exit; the library also no longer assumes the running server process is a child of caller process (by eliminating checks to the `Dolt.server` attribute); also added richer set of exceptions for helping user see root cause of failed server interactions
- #49 we now expose logging configurations inside `dolt.core` via `LOG_LEVEL` and `HANDLERS` variables, these are passed to a function for the logger factory that the library uses
- #16 README is now current
- #28 `clone_repo` is now `clone`, and it correctly implements the same behavior as the CLI for cloning a repo, that is the directory does not have to be explicitly passed
- retire command line shims that no one seems to use (they were awkward and ill considered)

### CODE REVIEW

**Comment by andrew-wm-arthur** [comment]
These changes look good, but they don't exactly solve the core problem. As we discussed this morning, we have to weigh the tradeoffs of using the sql-server to read/write the repo vs using the CLI. As I see it: 
- Both approaches require managing subprocesses, but the sql-server potentially requires managing multiple subprocesses and connections. 
- The sql-server allows us to use type inference and type checking features from the connector library. Using the CLI requires manually validating data and formatting it for write/import.
- In general, the sql-server is a much less tested pathway than other CLI commands. Using it here would provide more coverage, but at the cost of complicating development and testing of DoltPy.
I'm leaning toward the CLI out of simplicity/reliability. I think replicating the connector features is much closer at hand than stabilizing the sql-server

**Comment by oscarbatori** [comment]
@timsehn / @zachmu - do you guys have an opinion here?

**Comment by timsehn** [comment]
I like using the SQL server in doltpy. The problems are not going away because we avoid the path. This needs to work.

Maybe we can provide both interfaces and a switch? This means if one is blocked, you can try the other and see if it works. This will give us better repros.

For avoiding the MySQL client, we could use `dolt sql -r csv` as the read interafce. On the write path we could just assemble the queries and pipe in via `dolt sql < <file>`?

**Comment by zachmu** [comment]
The switch idea definitely seems like a good way to reproduce and debug problems as we keep working on this.

**Pull request merged**
